version: "3.8"
networks:
  backend-network:
    driver: bridge
services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    volumes:
      - db2:/data/db
    # ports:
    #   - 27017:27017
    networks:
      - backend-network

  backend:
    depends_on:
      - mongodb
    build: ./backend
    env_file: ./.env
    restart: unless-stopped
    ports:
      - 4000:4000 
    environment:
      - DB_HOST=mongodb
      - DB_PORT=27017
      - FE_URL=http://localhost:3000
    networks:
      - backend-network
# FOR SUBMISSION: Uncomment this and it will use NGINX to serve the frontend
  frontend:
    build: ./frontend
    ports:
      - 3000:80
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      - BE_API_URL=http://localhost:4000
volumes:
  db2: